#!/bin/bash
# One-click setup script for Crucible Community Edition
# This script generates .env file BEFORE docker-compose runs
# Run from project root: ./scripts/setup.sh

set -e

# Get the project root directory (parent of scripts/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

echo "=================================================="
echo "Crucible Community Edition - One-Click Setup"
echo "=================================================="
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "✓ .env file already exists"
    echo "  If you want to regenerate secrets, delete .env and run this script again"
    echo ""
    read -p "Continue with existing .env? (Y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]] && [[ ! $REPLY == "" ]]; then
        echo "Setup cancelled."
        exit 0
    fi
    echo ""
else
    echo "Generating secure secrets for first-time setup..."
    echo ""
    
    # Check if Python 3 is available
    if ! command -v python3 &> /dev/null; then
        echo "ERROR: python3 is required but not found."
        echo "Please install Python 3 and try again."
        exit 1
    fi
    
    # Generate secure random keys
    ENCRYPTION_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    JWT_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
    JWT_REFRESH_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
    AUTH_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(16))")
    POSTGRES_USER=$(python3 -c "import secrets, string; print(''.join(secrets.choice(string.ascii_lowercase + string.digits) for _ in range(12)))")
    POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")
    REDIS_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    
    # Create .env file
    cat > ".env" << EOF
# Crucible Community Edition Configuration
# Auto-generated by scripts/setup.sh - DO NOT EDIT MANUALLY unless you know what you're doing

# ============================================================================
# SECURITY - DO NOT SHARE THESE VALUES!
# ============================================================================

# API Key Encryption Key (32 characters)
# WARNING: If this changes, all encrypted API keys will become unreadable!
API_KEY_ENCRYPTION_KEY=$ENCRYPTION_KEY

# Community Edition Authentication Password
# Auto-generated secure password - save this value!
# For production, consider hashing: cd service && python -m scripts.hash_password <password>
ROUNDTABLE_COMMUNITY_AUTH_PASSWORD=$AUTH_PASSWORD

# JWT Secrets (used for token signing)
ROUNDTABLE_JWT_SECRET=$JWT_SECRET
ROUNDTABLE_JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET

# Database Credentials
# IMPORTANT: Save these values - you'll need them if you need to access the database directly
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Redis Credentials
# IMPORTANT: Save this value - Redis requires authentication
REDIS_PASSWORD=$REDIS_PASSWORD

# ============================================================================
# OPTIONAL - Provider API Keys (if you want server-side defaults)
# ============================================================================
# Users can also set their own API keys in the Settings page after login

# OpenRouter API Key (optional - users can provide their own)
ROUNDTABLE_OPENROUTER_API_KEY=

# Eden AI API Key (optional - for AI research features)
ROUNDTABLE_EDEN_AI_API_KEY=

# ============================================================================
# OPTIONAL - LLM Rate Limiting Configuration
# ============================================================================
# Configure rate limiting for LLM API calls to prevent exceeding provider limits.
# You can change this in .env file if needed.

# Enable Rate Limiting (default: true - rate limiting enabled)
ROUNDTABLE_ENABLE_RATE_LIMITING=true

# LLM Rate Limit (Tokens Per Minute) - default: 100000
ROUNDTABLE_LLM_RATE_LIMIT_TPM=100000

# LLM Rate Limit Window (Seconds) - default: 60 (one minute window)
ROUNDTABLE_LLM_RATE_LIMIT_WINDOW_SECONDS=60
EOF
    
    chmod 600 ".env"
    
    echo "✓ Secrets generated successfully!"
    echo ""
    echo "=================================================="
    echo "IMPORTANT: Save your credentials!"
    echo "=================================================="
    echo ""
    echo "Your secure credentials have been generated:"
    echo "  - Authentication password: $AUTH_PASSWORD"
    echo "  - Database user: $POSTGRES_USER"
    echo "  - Database password: $POSTGRES_PASSWORD"
    echo "  - Redis password: $REDIS_PASSWORD"
    echo ""
    echo "⚠️  These values are saved in: .env"
    echo "   Keep this file secure and never commit it to version control!"
    echo ""
fi

# Check if Docker is available
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker is required but not found."
    echo "Please install Docker and try again."
    exit 1
fi

if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo "ERROR: Docker Compose is required but not found."
    echo "Please install Docker Compose and try again."
    exit 1
fi

echo "=================================================="
echo "Starting Crucible Community Edition..."
echo "=================================================="
echo ""

# Use docker compose (newer) or docker-compose (older)
if docker compose version &> /dev/null; then
    COMPOSE_CMD="docker compose"
else
    COMPOSE_CMD="docker-compose"
fi

echo "Running: $COMPOSE_CMD up -d"
echo ""

# Start the services
$COMPOSE_CMD up -d

echo ""
echo "=================================================="
echo "Setup Complete!"
echo "=================================================="
echo ""
echo "Crucible Community Edition is starting..."
echo ""
echo "Access the application at:"
echo "  - Frontend: http://localhost:3000"
echo "  - API: http://localhost:8000"
echo "  - API Docs: http://localhost:8000/docs"
echo ""
echo "Default login credentials:"
echo "  - Email: admin@community.local"
if [ -f ".env" ] && grep -q "ROUNDTABLE_COMMUNITY_AUTH_PASSWORD=" .env; then
    PASSWORD=$(grep "ROUNDTABLE_COMMUNITY_AUTH_PASSWORD=" .env | cut -d '=' -f2)
    echo "  - Password: $PASSWORD"
    echo ""
    echo "⚠️  Save this password! It's stored in .env file"
else
    echo "  - Password: (check .env file for ROUNDTABLE_COMMUNITY_AUTH_PASSWORD)"
fi
echo ""
echo "To view logs: $COMPOSE_CMD logs -f"
echo "To stop: $COMPOSE_CMD down"
echo ""
