# One-click setup script for Crucible Community Edition (Windows PowerShell)
# This script generates .env file BEFORE docker-compose runs
# Run from project root: .\scripts\setup.ps1

# Get the project root directory (parent of scripts/)
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
Set-Location $ProjectRoot

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "Crucible Community Edition - One-Click Setup" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env already exists
if (Test-Path ".env") {
    Write-Host "✓ .env file already exists" -ForegroundColor Green
    Write-Host "  If you want to regenerate secrets, delete .env and run this script again"
    Write-Host ""
    $response = Read-Host "Continue with existing .env? (Y/n)"
    if ($response -ne "" -and $response -ne "Y" -and $response -ne "y") {
        Write-Host "Setup cancelled." -ForegroundColor Yellow
        exit 0
    }
    Write-Host ""
} else {
    Write-Host "Generating secure secrets for first-time setup..." -ForegroundColor Yellow
    Write-Host ""
    
    # Check if Python 3 is available
    try {
        $pythonVersion = python --version 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "Python not found"
        }
    } catch {
        Write-Host "ERROR: Python is required but not found." -ForegroundColor Red
        Write-Host "Please install Python 3 and try again."
        exit 1
    }
    
    # Generate secure random keys
    $ENCRYPTION_KEY = python -c "import secrets; print(secrets.token_urlsafe(32))"
    $JWT_SECRET = python -c "import secrets; print(secrets.token_urlsafe(48))"
    $JWT_REFRESH_SECRET = python -c "import secrets; print(secrets.token_urlsafe(48))"
    $AUTH_PASSWORD = python -c "import secrets; print(secrets.token_urlsafe(16))"
    $POSTGRES_USER = python -c "import secrets, string; print(''.join(secrets.choice(string.ascii_lowercase + string.digits) for _ in range(12)))"
    $POSTGRES_PASSWORD = python -c "import secrets; print(secrets.token_urlsafe(24))"
    $REDIS_PASSWORD = python -c "import secrets; print(secrets.token_urlsafe(32))"
    
    # Create .env file
    $envContent = @"
# Crucible Community Edition Configuration
# Auto-generated by scripts/setup.ps1 - DO NOT EDIT MANUALLY unless you know what you're doing

# ============================================================================
# SECURITY - DO NOT SHARE THESE VALUES!
# ============================================================================

# API Key Encryption Key (32 characters)
# WARNING: If this changes, all encrypted API keys will become unreadable!
API_KEY_ENCRYPTION_KEY=$ENCRYPTION_KEY

# Community Edition Authentication Password
# Auto-generated secure password - save this value!
# For production, consider hashing: cd service && python -m scripts.hash_password <password>
ROUNDTABLE_COMMUNITY_AUTH_PASSWORD=$AUTH_PASSWORD

# JWT Secrets (used for token signing)
ROUNDTABLE_JWT_SECRET=$JWT_SECRET
ROUNDTABLE_JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET

# Database Credentials
# IMPORTANT: Save these values - you'll need them if you need to access the database directly
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Redis Credentials
# IMPORTANT: Save this value - Redis requires authentication
REDIS_PASSWORD=$REDIS_PASSWORD

# ============================================================================
# OPTIONAL - Provider API Keys (if you want server-side defaults)
# ============================================================================
# Users can also set their own API keys in the Settings page after login

# OpenRouter API Key (optional - users can provide their own)
ROUNDTABLE_OPENROUTER_API_KEY=

# Eden AI API Key (optional - for AI research features)
ROUNDTABLE_EDEN_AI_API_KEY=

# ============================================================================
# OPTIONAL - LLM Rate Limiting Configuration
# ============================================================================
# Configure rate limiting for LLM API calls to prevent exceeding provider limits.
# You can change this in .env file if needed.

# Enable Rate Limiting (default: true - rate limiting enabled)
ROUNDTABLE_ENABLE_RATE_LIMITING=true

# LLM Rate Limit (Tokens Per Minute) - default: 100000
ROUNDTABLE_LLM_RATE_LIMIT_TPM=100000

# LLM Rate Limit Window (Seconds) - default: 60 (one minute window)
ROUNDTABLE_LLM_RATE_LIMIT_WINDOW_SECONDS=60
"@
    
    $envContent | Out-File -FilePath ".env" -Encoding utf8 -NoNewline
    (Get-Item ".env").Attributes = "Hidden"
    
    Write-Host "✓ Secrets generated successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "==================================================" -ForegroundColor Cyan
    Write-Host "IMPORTANT: Save your credentials!" -ForegroundColor Yellow
    Write-Host "==================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Your secure credentials have been generated:"
    Write-Host "  - Authentication password: $AUTH_PASSWORD"
    Write-Host "  - Database user: $POSTGRES_USER"
    Write-Host "  - Database password: $POSTGRES_PASSWORD"
    Write-Host "  - Redis password: $REDIS_PASSWORD"
    Write-Host ""
    Write-Host "⚠️  These values are saved in: .env" -ForegroundColor Yellow
    Write-Host "   Keep this file secure and never commit it to version control!" -ForegroundColor Yellow
    Write-Host ""
}

# Check if Docker is available
try {
    docker --version | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker not found"
    }
} catch {
    Write-Host "ERROR: Docker is required but not found." -ForegroundColor Red
    Write-Host "Please install Docker Desktop and try again."
    exit 1
}

# Check for docker compose
$composeCmd = "docker compose"
try {
    docker compose version | Out-Null
    if ($LASTEXITCODE -ne 0) {
        $composeCmd = "docker-compose"
    }
} catch {
    $composeCmd = "docker-compose"
}

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "Starting Crucible Community Edition..." -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "Running: $composeCmd up -d" -ForegroundColor Yellow
Write-Host ""

# Start the services
Invoke-Expression "$composeCmd up -d"

Write-Host ""
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Crucible Community Edition is starting..."
Write-Host ""
Write-Host "Access the application at:"
Write-Host "  - Frontend: http://localhost:3000"
Write-Host "  - API: http://localhost:8000"
Write-Host "  - API Docs: http://localhost:8000/docs"
Write-Host ""
Write-Host "Default login credentials:"
Write-Host "  - Email: admin@community.local"
if (Test-Path ".env") {
    $passwordLine = Get-Content ".env" | Select-String "ROUNDTABLE_COMMUNITY_AUTH_PASSWORD="
    if ($passwordLine) {
        $password = ($passwordLine -split "=")[1]
        Write-Host "  - Password: $password"
        Write-Host ""
        Write-Host "⚠️  Save this password! It's stored in .env file" -ForegroundColor Yellow
    } else {
        Write-Host "  - Password: (check .env file for ROUNDTABLE_COMMUNITY_AUTH_PASSWORD)"
    }
} else {
    Write-Host "  - Password: (check .env file for ROUNDTABLE_COMMUNITY_AUTH_PASSWORD)"
}
Write-Host ""
Write-Host "To view logs: $composeCmd logs -f"
Write-Host "To stop: $composeCmd down"
Write-Host ""
